name: bayesian  # for Bayesian analysis
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- missingno
- pymc3
- cython
- scikit-learn
- autopep8
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- jupyter
- jupyterlab
- ipykernel
- jupyterlab
- jupyter_contrib_nbextensions
- rise
- h5py
- pyjanitor
- openblas
