name: bayesian-analysis-recipes  # for Bayesian analysis
channels:
- conda-forge
dependencies:
- python=3.8
# Data Science Stack
- pymc3=3.8
- mkl-service
- theano
- arviz
- missingno
- pygpu
- scikit-learn
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- pyjanitor
# Jupyter
- jupyter
- jupyterlab
- ipykernel
- nbstripout
- rise
- jupytext
# Other
- pip
- pre-commit
- glances
- pyprojroot
- nodejs
- pip:
  - jax
  - jaxlib
  - -e git+https://github.com/pymc-devs/pymc4.git#egg=pymc4
  # - tfp-nightly
  - mkdocs
  - mkdocs-minify-plugin
  - pymdown-extensions
  - mkdocs-material
  - mknotebooks
